version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI"
      - yum install awscli -y
  pre_build:
    commands:
      - echo "Changing directory to source"
      - cd $CODEBUILD_SRC_DIR/Deployment
  build:
    commands:
      - echo "Deploying architecture"
      - aws cloudformation create-stack --stack_name FirstEphemeralEnvironment --template-body file://EC2Cloudformation.yaml
      - echo "Finished deployment of infrastructure"
  post_build:
    commands:
      - echo "Build has finished successfully"